// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_banner_ad_shown = "CgkI352R6rEXEAIQAQ"; // <GPGSID>
        public const string achievement_ads_ads_ads = "CgkI352R6rEXEAIQBQ"; // <GPGSID>
        public const string achievement_rewarded_ads_shown = "CgkI352R6rEXEAIQAw"; // <GPGSID>
        public const string achievement_achivement = "CgkI352R6rEXEAIQBA"; // <GPGSID>
        public const string achievement_interstitial_ad_shown = "CgkI352R6rEXEAIQAg"; // <GPGSID>
        public const string leaderboard_score = "CgkI352R6rEXEAIQBg"; // <GPGSID>

}

